apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
spec:
  version: v1.24.3
  namespace: istio-system
  profile: ambient
  values:
    pilot:
      trustedZtunnelNamespace: istio-system
    meshConfig:
      enableTracing: true
      extensionProviders:
      - name: otel
        opentelemetry:
          port: 4317
          service: dev-collector.istio-system.svc.cluster.local
      defaultProviders:
        tracing:
          - otel
    gateways:
      istio-ingressgateway:
        type: LoadBalancer
        labels:
          istio: ingressgateway
        enabled: true
