{{- range $apps := .Values.apps }}
{{ $version := $.Values.appVersion }}
{{- with $img := $.Values.image }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $apps.name }}-{{ $version }}
  namespace: travel-portal
  labels:
    app: {{ $apps.name }}
spec:
  selector:
    matchLabels:
      app: {{ $apps.name }}
      version: {{ $version }}
  replicas: {{ $.Values.replicaCount }}
  template:
    metadata:
      annotations:
      {{- include "travel-portal.istioProxyConfig" . | nindent 8 }}
      labels:
        app: {{ $apps.name }}
        version: {{ $version }}
    spec:
      containers:
        {{- if eq $apps.name "voyages" }}
        - name: {{ $apps.name }}
        {{- else }}
        - name: control
        {{- end }}
          image: {{ $img.registry }}/{{ $img.repository }}/demo_travels_portal:{{ $img.tag }}
          imagePullPolicy: {{ $img.pullPolicy }}
          ports:
            - containerPort: {{ $.Values.service.port }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
          env:
          {{- with $apps.env }}
            - name: LISTEN_ADDRESS
              value: ":8000"
            - name: PORTAL_COORDINATES
              value: {{ .coordinates | quote }}
            - name: PORTAL_COUNTRY
              value: {{ .country | quote }}
            - name: PORTAL_NAME
              value: "{{ $apps.name }}.{{ .countryShort }}"
            - name: TRAVELS_AGENCY_SERVICE
              value: "http://travels.travel-agency:8000"
          {{- end }}
{{- end }}
{{- end }}
