clusterGroup:
  name: hub
  isHubCluster: true

  namespaces:
    - vault
    - golang-external-secrets
    - travel-agency:
        labels:
          istio-discovery: enabled
          istio.io/rev: default
    - travel-portal:
        labels:
          istio-discovery: enabled
          istio.io/rev: default
    - travel-control:
        labels:
          istio-discovery: enabled
          istio.io/rev: default
    - istio-system:
        labels:
          istio-discovery: enabled
    - tempo:
        labels:
          istio-discovery: enabled
    - openshift-tempo-operator:
        labels:
          openshift.io/cluster-monitoring: true
        operatorGroup: true
        targetNamespaces:
    - openshift-opentelemetry-operator:
        operatorGroup: true
        targetNamespaces:
    - openshift-cluster-observability-operator:
        labels:
          openshift.io/cluster-monitoring: true
        operatorGroup: true
        targetNamespaces:

  subscriptions:
    servicemesh:
      name: servicemeshoperator3
    servicemesh-console:
      name: kiali-ossm
    distributed-tracing:
      name: tempo-product
      namespace: openshift-tempo-operator
    opentelemetry:
      name: opentelemetry-product
      namespace: openshift-opentelemetry-operator
    cluster-observability:
      name: cluster-observability-operator
      namespace: openshift-cluster-observability-operator

  projects:
    - hub
    - servicemesh
    - travelops
    - distributed-tracing

  applications:
    vault:
      name: vault
      namespace: vault
      project: hub
      chart: hashicorp-vault
      chartVersion: 0.1.*
    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      project: hub
      chart: golang-external-secrets
      chartVersion: 0.1.*
    mysql:
      name: mysqldb
      namespace: travel-agency
      project: travelops
      path: charts/all/travelops/mysqldb
    agency:
      name: travel-agency
      namespace: travel-agency
      project: travelops
      path: charts/all/travelops/travel-agency
    portal:
      name: travel-portal
      namespace: travel-portal
      project: travelops
      path: charts/all/travelops/travel-portal
    control:
      name: travel-control
      namespace: travel-control
      project: travelops
      path: charts/all/travelops/travel-control
    servicemesh:
      name: servicemesh
      namespace: istio-system
      project: servicemesh
      chart: servicemesh
      chartVersion: 0.1.*
    temposttack:
      name: tempostack
      namespace: tempo
      project: distributed-tracing
      path: charts/all/tempostack
      extraValueFiles:
        - /values-distributed-tracing.yaml
    tracing:
      name: distributed-tracing
      namespace: istio-system
      project: distributed-tracing
      path: charts/all/distributed-tracing
      extraValueFiles:
        - /values-distributed-tracing.yaml

servicemesh:
  istio:
    values:
      meshConfig:
        enableTracing: true
        extensionProviders:
          - name: zipkin
            zipkin:
              service: dev-collector.istio-system.svc.cluster.local
              port: 9411
        defaultProviders:
          tracing:
            - zipkin
        discoverySelectors:
          - matchLabels:
              istio-discovery: enabled
  peerauthentications:
    - name: default
      namespace: istio-system
      spec:
        mtls:
          mode: STRICT
  monitoring:
    enabled: true
    podMonitorNamespaces:
      - travel-agency
      - travel-portal
      - travel-control
