apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: mesh-default
  namespace: istio-system
spec:
  tracing:
    - providers:
        - name: otel
      randomSamplingPercentage: 100
      customTags:
        http.header.portal:
          header:
            name: portal
        http.header.device:
          header:
            name: device
        http.header.user:
          header:
            name: user
        http.header.travel:
          header:
            name: travel
      propagation:
        - B3
  metrics:
    - providers:
        - name: prometheus
