{{- range .Values.tracing.collectors }}
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  config: |
{{ .config | indent 4 }}
---
{{- end }}
