---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: control
  namespace: travel-control
  labels:
    app: control
spec:
  selector:
    matchLabels:
      app: control
      version: {{ .Values.appVersion }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
      {{- include "travel-control.istioProxyConfig" . | nindent 8 }}
      labels:
        app: control
        version: {{ .Values.appVersion }}
    spec:
      containers:
      {{- with $img := .Values.image }}
        - name: control
          image: {{ $img.registry }}/{{ $img.repository }}/demo_travels_control:{{ $img.tag }}
          imagePullPolicy: {{ $img.pullPolicy }}
      {{- end }}
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
          env:
            - name: PORTAL_SERVICES
              value: "voyages.fr;http://voyages.travel-portal:8000,viaggi.it;http://viaggi.travel-portal:8000,travels.uk;http://travels.travel-portal:8000"
