apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
  name: rollout-restart
  namespace: travel-control
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - image: {{ .Values.job.image }}
        name: rollout-restart
        command:
          - /bin/bash
          - '/usr/local/bin/rollout-restart.sh'
        volumeMounts:
        - mountPath: /usr/local/bin/rollout-restart.sh
          name: rollout-restart
          subPath: rollout-restart.sh
      volumes:
        - name: rollout-restart
          configMap:
            name: rollout-restart
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.rbac.serviceAccountName }}
      terminationGracePeriodSeconds: 400
