apiVersion: v2
name: distributed-tracing
description: |
  Deploys OpenTelemetry Collector, mesh-wide telemetry, and console integration
  for distributed tracing in OpenShift Service Mesh 3 environments. A multi-tenant
  tempostack is expected to use the tracing console plugin.

type: application
version: 0.1.0
appVersion: "1.0.0"
